/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check Refresh Token */
        get: operations["check_refresh_token_api_v1_auth_refresh_check_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Authenticated User Profile */
        get: operations["get_authenticated_user_profile_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Authenticated User Profile */
        patch: operations["update_authenticated_user_profile_api_v1_users_me_update_patch"];
        trace?: never;
    };
    "/api/v1/messages/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of messages */
        get: operations["get_messages_list_api_v1_messages__get"];
        put?: never;
        /** Create new message */
        post: operations["create_message_api_v1_messages__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/messages/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get specific message by id */
        get: operations["get_message_api_v1_messages__message_id__get"];
        put?: never;
        post?: never;
        /** Delete new message */
        delete: operations["delete_message_api_v1_messages__message_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Categories List */
        get: operations["get_categories_list_api_v1_categories_get"];
        put?: never;
        /** Create Category */
        post: operations["create_category_api_v1_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/by-slugs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Categories List By Slugs */
        get: operations["get_categories_list_by_slugs_api_v1_categories_by_slugs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Category */
        delete: operations["delete_category_api_v1_categories__category_id__delete"];
        options?: never;
        head?: never;
        /** Update Category */
        patch: operations["update_category_api_v1_categories__category_id__patch"];
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Products List */
        get: operations["get_products_list_api_v1_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/by-ids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Products By Likes List */
        get: operations["get_products_by_likes_list_api_v1_products_by_ids_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/unique": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Unique Product List */
        get: operations["get_unique_product_list_api_v1_products_unique_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch Filters */
        get: operations["fetch_filters_api_v1_products_filters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/popular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Products Recommendations */
        get: operations["get_products_recommendations_api_v1_products_popular_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch Absolute Product */
        get: operations["fetch_absolute_product_api_v1_products__product_slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Product */
        post: operations["create_product_api_v1_products__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Product */
        patch: operations["update_product_api_v1_products__product_id__patch"];
        trace?: never;
    };
    "/api/v1/products/unique/{unique_product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Unique */
        delete: operations["delete_unique_api_v1_products_unique__unique_product_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cart */
        get: operations["get_cart_api_v1_cart_get"];
        put?: never;
        /** Add To Cart */
        post: operations["add_to_cart_api_v1_cart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cart/change-item-quantity/{cart_item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Cart Item Quantity */
        patch: operations["update_cart_item_quantity_api_v1_cart_change_item_quantity__cart_item_id__patch"];
        trace?: never;
    };
    "/api/v1/cart/{cart_item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Item From Cart */
        delete: operations["remove_item_from_cart_api_v1_cart__cart_item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/faq": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Faqs List */
        get: operations["get_faqs_list_api_v1_faq_get"];
        put?: never;
        /** Create Faq */
        post: operations["create_faq_api_v1_faq_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/faq/{faq_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Faq */
        get: operations["get_faq_api_v1_faq__faq_id__get"];
        put?: never;
        post?: never;
        /** Delete Faq */
        delete: operations["delete_faq_api_v1_faq__faq_id__delete"];
        options?: never;
        head?: never;
        /** Update Faq */
        patch: operations["update_faq_api_v1_faq__faq_id__patch"];
        trace?: never;
    };
    "/api/v1/like": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Likes List */
        get: operations["get_likes_list_api_v1_like_get"];
        put?: never;
        /** Create Like */
        post: operations["create_like_api_v1_like_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/like/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Like */
        delete: operations["delete_like_api_v1_like__product_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Orders List */
        get: operations["get_orders_list_api_v1_orders_get"];
        put?: never;
        /** Create Order */
        post: operations["create_order_api_v1_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Orders History */
        get: operations["get_orders_history_api_v1_orders_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Active Orders */
        get: operations["get_active_orders_api_v1_orders_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Order Info */
        patch: operations["update_order_info_api_v1_orders__order_id__patch"];
        trace?: never;
    };
    "/api/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ping */
        get: operations["ping_api_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiResponseSchema[ListPaginatedResponse[ReadExtendedOrderSchema]] */
        ApiResponseSchema_ListPaginatedResponse_ReadExtendedOrderSchema__: {
            /** Data */
            data?: components["schemas"]["ListPaginatedResponse_ReadExtendedOrderSchema_"] | Record<string, never>;
            /** Meta */
            meta?: Record<string, never>;
            /** Errors */
            errors?: components["schemas"]["ErrorDetail"][];
        };
        /** ApiResponseSchema[ListPaginatedResponse[ReadFullUniqueProductSchema]] */
        ApiResponseSchema_ListPaginatedResponse_ReadFullUniqueProductSchema__: {
            /** Data */
            data?: components["schemas"]["ListPaginatedResponse_ReadFullUniqueProductSchema_"] | Record<string, never>;
            /** Meta */
            meta?: Record<string, never>;
            /** Errors */
            errors?: components["schemas"]["ErrorDetail"][];
        };
        /** ApiResponseSchema[ListPaginatedResponse[ReadMessageSchema]] */
        ApiResponseSchema_ListPaginatedResponse_ReadMessageSchema__: {
            /** Data */
            data?: components["schemas"]["ListPaginatedResponse_ReadMessageSchema_"] | Record<string, never>;
            /** Meta */
            meta?: Record<string, never>;
            /** Errors */
            errors?: components["schemas"]["ErrorDetail"][];
        };
        /** ApiResponseSchema[ListPaginatedResponse[ReadPreviewProductSchema]] */
        ApiResponseSchema_ListPaginatedResponse_ReadPreviewProductSchema__: {
            /** Data */
            data?: components["schemas"]["ListPaginatedResponse_ReadPreviewProductSchema_"] | Record<string, never>;
            /** Meta */
            meta?: Record<string, never>;
            /** Errors */
            errors?: components["schemas"]["ErrorDetail"][];
        };
        /** ApiResponseSchema[ReadAbsoluteProductSchema] */
        ApiResponseSchema_ReadAbsoluteProductSchema_: {
            /** Data */
            data?: components["schemas"]["ReadAbsoluteProductSchema"] | Record<string, never>;
            /** Meta */
            meta?: Record<string, never>;
            /** Errors */
            errors?: components["schemas"]["ErrorDetail"][];
        };
        /** ApiResponseSchema[ReadCartItemSchema] */
        ApiResponseSchema_ReadCartItemSchema_: {
            /** Data */
            data?: components["schemas"]["ReadCartItemSchema"] | Record<string, never>;
            /** Meta */
            meta?: Record<string, never>;
            /** Errors */
            errors?: components["schemas"]["ErrorDetail"][];
        };
        /** ApiResponseSchema[ReadCategorySchema] */
        ApiResponseSchema_ReadCategorySchema_: {
            /** Data */
            data?: components["schemas"]["ReadCategorySchema"] | Record<string, never>;
            /** Meta */
            meta?: Record<string, never>;
            /** Errors */
            errors?: components["schemas"]["ErrorDetail"][];
        };
        /** ApiResponseSchema[ReadFAQSchema] */
        ApiResponseSchema_ReadFAQSchema_: {
            /** Data */
            data?: components["schemas"]["ReadFAQSchema"] | Record<string, never>;
            /** Meta */
            meta?: Record<string, never>;
            /** Errors */
            errors?: components["schemas"]["ErrorDetail"][];
        };
        /** ApiResponseSchema[ReadFiltersSchema] */
        ApiResponseSchema_ReadFiltersSchema_: {
            /** Data */
            data?: components["schemas"]["ReadFiltersSchema"] | Record<string, never>;
            /** Meta */
            meta?: Record<string, never>;
            /** Errors */
            errors?: components["schemas"]["ErrorDetail"][];
        };
        /** ApiResponseSchema[ReadFullCartSchema] */
        ApiResponseSchema_ReadFullCartSchema_: {
            /** Data */
            data?: components["schemas"]["ReadFullCartSchema"] | Record<string, never>;
            /** Meta */
            meta?: Record<string, never>;
            /** Errors */
            errors?: components["schemas"]["ErrorDetail"][];
        };
        /** ApiResponseSchema[ReadLikeSchema] */
        ApiResponseSchema_ReadLikeSchema_: {
            /** Data */
            data?: components["schemas"]["ReadLikeSchema"] | Record<string, never>;
            /** Meta */
            meta?: Record<string, never>;
            /** Errors */
            errors?: components["schemas"]["ErrorDetail"][];
        };
        /** ApiResponseSchema[ReadMessageSchema] */
        ApiResponseSchema_ReadMessageSchema_: {
            /** Data */
            data?: components["schemas"]["ReadMessageSchema"] | Record<string, never>;
            /** Meta */
            meta?: Record<string, never>;
            /** Errors */
            errors?: components["schemas"]["ErrorDetail"][];
        };
        /** ApiResponseSchema[ReadOrderBaseSchema] */
        ApiResponseSchema_ReadOrderBaseSchema_: {
            /** Data */
            data?: components["schemas"]["ReadOrderBaseSchema"] | Record<string, never>;
            /** Meta */
            meta?: Record<string, never>;
            /** Errors */
            errors?: components["schemas"]["ErrorDetail"][];
        };
        /** ApiResponseSchema[ReadUserSchema] */
        ApiResponseSchema_ReadUserSchema_: {
            /** Data */
            data?: components["schemas"]["ReadUserSchema"] | Record<string, never>;
            /** Meta */
            meta?: Record<string, never>;
            /** Errors */
            errors?: components["schemas"]["ErrorDetail"][];
        };
        /** ApiResponseSchema[list[ReadCategorySchema]] */
        ApiResponseSchema_list_ReadCategorySchema__: {
            /** Data */
            data?: components["schemas"]["ReadCategorySchema"][] | Record<string, never>;
            /** Meta */
            meta?: Record<string, never>;
            /** Errors */
            errors?: components["schemas"]["ErrorDetail"][];
        };
        /** ApiResponseSchema[list[ReadExtendedOrderSchema]] */
        ApiResponseSchema_list_ReadExtendedOrderSchema__: {
            /** Data */
            data?: components["schemas"]["ReadExtendedOrderSchema"][] | Record<string, never>;
            /** Meta */
            meta?: Record<string, never>;
            /** Errors */
            errors?: components["schemas"]["ErrorDetail"][];
        };
        /** ApiResponseSchema[list[ReadFAQSchema]] */
        ApiResponseSchema_list_ReadFAQSchema__: {
            /** Data */
            data?: components["schemas"]["ReadFAQSchema"][] | Record<string, never>;
            /** Meta */
            meta?: Record<string, never>;
            /** Errors */
            errors?: components["schemas"]["ErrorDetail"][];
        };
        /** ApiResponseSchema[list[ReadPreviewProductSchema]] */
        ApiResponseSchema_list_ReadPreviewProductSchema__: {
            /** Data */
            data?: components["schemas"]["ReadPreviewProductSchema"][] | Record<string, never>;
            /** Meta */
            meta?: Record<string, never>;
            /** Errors */
            errors?: components["schemas"]["ErrorDetail"][];
        };
        /** ApiResponseSchema[list[int]] */
        ApiResponseSchema_list_int__: {
            /** Data */
            data?: number[] | Record<string, never>;
            /** Meta */
            meta?: Record<string, never>;
            /** Errors */
            errors?: components["schemas"]["ErrorDetail"][];
        };
        /** ApiResponseSchema[list[list[str, str]]] */
        ApiResponseSchema_list_list_str__str___: {
            /** Data */
            data?: string[][] | Record<string, never>;
            /** Meta */
            meta?: Record<string, never>;
            /** Errors */
            errors?: components["schemas"]["ErrorDetail"][];
        };
        /** Body_create_product_api_v1_products__post */
        Body_create_product_api_v1_products__post: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Description */
            description?: string | null;
            /** Category Id */
            category_id: number;
            /** Images */
            images: string[];
            /** Variations Json */
            variations_json: string;
        };
        /** Body_update_product_api_v1_products__product_id__patch */
        Body_update_product_api_v1_products__product_id__patch: {
            /** Name */
            name?: string | null;
            /** Slug */
            slug?: string | null;
            /** Description */
            description?: string | null;
            /** Category Id */
            category_id?: number | null;
            /** New Images */
            new_images?: string[] | null;
            /** Delete Image Ids */
            delete_image_ids?: string | null;
            /** Variations Json */
            variations_json?: string | null;
        };
        /** CreateCartItemWithoutCartIdSchema */
        CreateCartItemWithoutCartIdSchema: {
            /** Quantity */
            quantity: number;
            /** Product Id */
            product_id: number;
        };
        /** CreateCategorySchema */
        CreateCategorySchema: {
            /**
             * Name
             * @example Одностінні труби
             */
            name: string;
            /**
             * Slug
             * @example odnostinni-trybu
             */
            slug: string;
            /** File Path */
            file_path?: string | null;
            /**
             * Parent Id
             * @example 0
             */
            parent_id?: number | null;
        };
        /** CreateFAQSchema */
        CreateFAQSchema: {
            /**
             * Youtube Url
             * @example https://www.youtube.com/watch?v=-yIsQPp31L0&ab_channel=ByteGrad
             */
            youtube_url?: string | null;
            /**
             * Question
             * @example Як скинути пароль?
             */
            question: string;
            /**
             * Answer
             * @example Перейдіть до налаштувань...
             */
            answer: string;
        };
        /** CreateMessageSchema */
        CreateMessageSchema: {
            /**
             * Name of the user
             * @example Іван
             */
            user_name: string;
            /**
             * Phone number of the user
             * @example 0991234567
             */
            phone_number: string;
            /**
             * Message from the user
             * @example Привіт!
             */
            message?: string | null;
        };
        /** CreateOrderSchema */
        CreateOrderSchema: {
            /** First Name */
            first_name?: string;
            /** Last Name */
            last_name?: string;
            /** Patronymic */
            patronymic?: string;
            /** Phone Number */
            phone_number?: string;
            /** Email address of the user */
            email?: string | null;
            /**
             * Address
             * @description 5-200 characters
             */
            address: string;
            /**
             * Shipping Method
             * @description Invalid shipping method
             */
            shipping_method: string;
            /**
             * Payment Method
             * @description Invalid payment method
             */
            payment_method: string;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Meta */
            meta?: Record<string, never> | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ListPaginatedResponse[ReadExtendedOrderSchema] */
        ListPaginatedResponse_ReadExtendedOrderSchema_: {
            /** Items */
            items: components["schemas"]["ReadExtendedOrderSchema"][];
            pagination: components["schemas"]["PaginationOut"];
        };
        /** ListPaginatedResponse[ReadFullUniqueProductSchema] */
        ListPaginatedResponse_ReadFullUniqueProductSchema_: {
            /** Items */
            items: components["schemas"]["ReadFullUniqueProductSchema"][];
            pagination: components["schemas"]["PaginationOut"];
        };
        /** ListPaginatedResponse[ReadMessageSchema] */
        ListPaginatedResponse_ReadMessageSchema_: {
            /** Items */
            items: components["schemas"]["ReadMessageSchema"][];
            pagination: components["schemas"]["PaginationOut"];
        };
        /** ListPaginatedResponse[ReadPreviewProductSchema] */
        ListPaginatedResponse_ReadPreviewProductSchema_: {
            /** Items */
            items: components["schemas"]["ReadPreviewProductSchema"][];
            pagination: components["schemas"]["PaginationOut"];
        };
        /** LoginUserSchema */
        LoginUserSchema: {
            /** User's password for registration */
            password: string;
            /** Username */
            username: string;
        };
        /** PaginationOut */
        PaginationOut: {
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Total */
            total: number;
        };
        /** PingResponseSchema */
        PingResponseSchema: {
            /** Result */
            result: boolean;
        };
        /** ReadAbsoluteProductSchema */
        ReadAbsoluteProductSchema: {
            /** Id */
            id: number;
            /**
             * Name
             * @example Sample Product
             */
            name: string;
            /**
             * Slug
             * @example sample-product
             */
            slug: string;
            /**
             * Description
             * @example This is a sample product description.
             */
            description?: string | null;
            /**
             * Category Id
             * @example 1
             */
            category_id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Images */
            images: components["schemas"]["ReadProductImageSchema"][];
            /** Variations */
            variations: components["schemas"]["ReadProductVariationSchema"][];
            /** Categories */
            categories?: [
                string,
                string
            ][] | null;
        };
        /** ReadCartItemSchema */
        ReadCartItemSchema: {
            /** Id */
            id: number;
            /** Cart Id */
            cart_id: number;
            /** Quantity */
            quantity: number;
            /** Product Id */
            product_id: number;
        };
        /** ReadCartItemWithTotalPriceSchema */
        ReadCartItemWithTotalPriceSchema: {
            /** Id */
            id: number;
            /** Cart Id */
            cart_id: number;
            /** Quantity */
            quantity: number;
            product: components["schemas"]["ReadPreviewProductSchema"];
            /** Total Price */
            total_price: number;
        };
        /** ReadCategorySchema */
        ReadCategorySchema: {
            /**
             * Name
             * @example Одностінні труби
             */
            name: string;
            /**
             * Slug
             * @example odnostinni-trybu
             */
            slug: string;
            /** File Path */
            file_path?: string | null;
            /**
             * Parent Id
             * @example 0
             */
            parent_id?: number | null;
            /** Id */
            id: number;
        };
        /** ReadExtendedOrderSchema */
        ReadExtendedOrderSchema: {
            /** First Name */
            first_name?: string;
            /** Last Name */
            last_name?: string;
            /** Patronymic */
            patronymic?: string;
            /** Phone Number */
            phone_number?: string;
            /** Email address of the user */
            email?: string | null;
            /**
             * Address
             * @description 5-200 characters
             */
            address: string;
            /**
             * Shipping Method
             * @description Invalid shipping method
             */
            shipping_method: string;
            /**
             * Payment Method
             * @description Invalid payment method
             */
            payment_method: string;
            /**
             * Id
             * @description Order ID
             */
            id: number;
            /**
             * Status
             * @description Invalid order status
             */
            status: string;
            /** Waybill Number */
            waybill_number?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Price Discount
             * @default 0
             */
            price_discount: number;
            /** Items */
            items: components["schemas"]["ReadOrderItemSchema"][];
            /**
             * Total Price
             * @description Non-negative value
             */
            total_price: number;
            /**
             * Total Quantity
             * @description Non-negative value
             */
            total_quantity: number;
        };
        /** ReadFAQSchema */
        ReadFAQSchema: {
            /**
             * Youtube Url
             * @example https://www.youtube.com/watch?v=-yIsQPp31L0&ab_channel=ByteGrad
             */
            youtube_url?: string | null;
            /**
             * Question
             * @example Як скинути пароль?
             */
            question: string;
            /**
             * Answer
             * @example Перейдіть до налаштувань...
             */
            answer: string;
            /** Id */
            id: number;
            /**
             * Embed Url
             * @example https://www.youtube.com/embed/dQw4w9WgXcQ
             */
            embed_url?: string | null;
        };
        /** ReadFiltersSchema */
        ReadFiltersSchema: {
            /** Diameter */
            diameter: string | null;
            /** Length */
            length: string | null;
            /** Thickness */
            thickness: string | null;
            /** Angle */
            angle: string | null;
            /** Metal Type */
            metal_type: string | null;
            /** Min Price */
            min_price: string | null;
            /** Max Price */
            max_price: string | null;
        };
        /** ReadFullCartSchema */
        ReadFullCartSchema: {
            /** Id */
            id: number;
            /** Items */
            items: components["schemas"]["ReadCartItemWithTotalPriceSchema"][];
            /** Total Price */
            total_price: number;
            /** Total Quantity */
            total_quantity: number;
        };
        /** ReadFullUniqueProductSchema */
        ReadFullUniqueProductSchema: {
            /** Id */
            id: number;
            /**
             * Name
             * @example Sample Product
             */
            name: string;
            /**
             * Slug
             * @example sample-product
             */
            slug: string;
            /**
             * Description
             * @example This is a sample product description.
             */
            description?: string | null;
            /**
             * Category Id
             * @example 1
             */
            category_id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Images */
            images: components["schemas"]["ReadProductImageSchema"][];
        };
        /** ReadLikeSchema */
        ReadLikeSchema: {
            /** User Id */
            user_id: number;
            /** Product Id */
            product_id: number;
            /** Id */
            id: number;
        };
        /** ReadMessageSchema */
        ReadMessageSchema: {
            /**
             * Name of the user
             * @example Іван
             */
            user_name: string;
            /**
             * Phone number of the user
             * @example 0991234567
             */
            phone_number: string;
            /**
             * Message from the user
             * @example Привіт!
             */
            message?: string | null;
            /** Id */
            id: number;
            /**
             * Timestamp when the message was created
             * Format: date-time
             */
            created_at: string;
        };
        /** ReadOrderBaseSchema */
        ReadOrderBaseSchema: {
            /** First Name */
            first_name?: string;
            /** Last Name */
            last_name?: string;
            /** Patronymic */
            patronymic?: string;
            /** Phone Number */
            phone_number?: string;
            /** Email address of the user */
            email?: string | null;
            /**
             * Address
             * @description 5-200 characters
             */
            address: string;
            /**
             * Shipping Method
             * @description Invalid shipping method
             */
            shipping_method: string;
            /**
             * Payment Method
             * @description Invalid payment method
             */
            payment_method: string;
            /**
             * Id
             * @description Order ID
             */
            id: number;
            /**
             * Status
             * @description Invalid order status
             */
            status: string;
            /** Waybill Number */
            waybill_number?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Price Discount
             * @default 0
             */
            price_discount: number;
        };
        /** ReadOrderItemSchema */
        ReadOrderItemSchema: {
            /**
             * Order Id
             * @description Must be positive integer
             */
            order_id: number;
            /**
             * Quantity
             * @description At least 1 item
             */
            quantity: number;
            /**
             * Price At Order
             * @description Must be positive value
             */
            price_at_order: number;
            /**
             * Id
             * @description Order item ID
             */
            id: number;
            product: components["schemas"]["ReadProductSchema"];
        };
        /** ReadPreviewProductSchema */
        ReadPreviewProductSchema: {
            /**
             * Name
             * @example Sample Product
             */
            name: string;
            /**
             * Slug
             * @example sample-product
             */
            slug: string;
            /**
             * Description
             * @example This is a sample product description.
             */
            description?: string | null;
            /**
             * Price
             * @example 19.99
             */
            price: number;
            /** Extra Attrs */
            extra_attrs: Record<string, never> | null;
            /**
             * Category Id
             * @example 1
             */
            category_id: number;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Discount Price
             * @example 19.99
             */
            discount_price: number;
            /**
             * Discount Percentage
             * @example 20
             */
            discount_percentage: number;
            /** Diameter */
            diameter: string | null;
            /** Length */
            length: string | null;
            /** Thickness */
            thickness: string | null;
            /** Angle */
            angle: string | null;
            /** Metal Type */
            metal_type: string | null;
            preview: components["schemas"]["ReadProductImageSchema"] | null;
        };
        /** ReadProductImageSchema */
        ReadProductImageSchema: {
            /**
             * File Path
             * @example /images/products/sample.jpg
             */
            file_path: string;
            /**
             * Alt
             * @example Sample product image
             */
            alt?: string | null;
            /**
             * Product Id
             * @example 1
             */
            product_id: number;
            /** Id */
            id: number;
            /** Filename */
            filename: string;
        };
        /** ReadProductSchema */
        ReadProductSchema: {
            /**
             * Name
             * @example Sample Product
             */
            name: string;
            /**
             * Slug
             * @example sample-product
             */
            slug: string;
            /**
             * Description
             * @example This is a sample product description.
             */
            description?: string | null;
            /**
             * Price
             * @example 19.99
             */
            price: number;
            /** Extra Attrs */
            extra_attrs: Record<string, never> | null;
            /**
             * Category Id
             * @example 1
             */
            category_id: number;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Discount Price
             * @example 19.99
             */
            discount_price: number;
            /**
             * Discount Percentage
             * @example 20
             */
            discount_percentage: number;
            /** Diameter */
            diameter: string | null;
            /** Length */
            length: string | null;
            /** Thickness */
            thickness: string | null;
            /** Angle */
            angle: string | null;
            /** Metal Type */
            metal_type: string | null;
        };
        /** ReadProductVariationSchema */
        ReadProductVariationSchema: {
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Price
             * @example 19.99
             */
            price: number;
            /**
             * Discount Price
             * @example 19.99
             */
            discount_price: number;
            /**
             * Discount Percentage
             * @example 20
             */
            discount_percentage: number;
            /** Diameter */
            diameter: string | null;
            /** Length */
            length: string | null;
            /** Thickness */
            thickness: string | null;
            /** Angle */
            angle: string | null;
            /** Metal Type */
            metal_type: string | null;
        };
        /** ReadUserSchema */
        ReadUserSchema: {
            /** Email address of the user */
            email?: string | null;
            /** Phone Number */
            phone_number?: string | null;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Patronymic */
            patronymic?: string | null;
            /** Username */
            username: string;
            /** Id */
            id: number;
            /**
             * Indicates if the user is active
             * @default true
             */
            is_active: boolean;
            /**
             * Indicates if the user is a superuser
             * @default false
             */
            is_superuser: boolean;
            /**
             * Indicates if the user is verified
             * @default false
             */
            is_verified: boolean;
            /**
             * Timestamp when the post was created
             * Format: date-time
             */
            created_at?: string;
            /**
             * Timestamp when the post was last updated
             * Format: date-time
             */
            updated_at?: string;
        };
        /** RegisterUserSchema */
        RegisterUserSchema: {
            /** User's password for registration */
            password: string;
            /** Email address of the user */
            email?: string | null;
            /** Phone Number */
            phone_number?: string | null;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Patronymic */
            patronymic?: string | null;
            /** Username */
            username: string;
            /** User's confirm password for registration */
            confirm_password: string;
        };
        /** TokenInfoSchema */
        TokenInfoSchema: {
            /** Access Token */
            access_token: string;
            /**
             * Access Token Expire Seconds
             * @default 3540
             */
            access_token_expire_seconds: number;
            /**
             * Token Type
             * @default Bearer
             */
            token_type: string;
        };
        /** UpdadeFAQSchema */
        UpdadeFAQSchema: {
            /**
             * Youtube Url
             * @example https://www.youtube.com/watch?v=-yIsQPp31L0&ab_channel=ByteGrad
             */
            youtube_url?: string | null;
            /**
             * Question
             * @example Як скинути пароль?
             */
            question?: string | null;
            /**
             * Answer
             * @example Перейдіть до налаштувань...
             */
            answer?: string | null;
        };
        /** UpdateCartItemQuantity */
        UpdateCartItemQuantity: {
            /** Action */
            action: string;
            /** Quantity */
            quantity: number;
        };
        /** UpdateCategorySchema */
        UpdateCategorySchema: {
            /**
             * Name
             * @example Одностінні труби
             */
            name?: string | null;
            /**
             * Slug
             * @example odnostinni-trybu
             */
            slug?: string | null;
            /** File Path */
            file_path?: string | null;
            /**
             * Parent Id
             * @example 0
             */
            parent_id?: number | null;
        };
        /** UpdateOrderSchema */
        UpdateOrderSchema: {
            /**
             * Status
             * @description Invalid order status
             * @default pending
             */
            status: string | null;
            /** Waybill Number */
            waybill_number?: string | null;
            /** Price Discount */
            price_discount: number;
        };
        /** UserUpdateWithPasswordSchema */
        UserUpdateWithPasswordSchema: {
            /** Email address of the user */
            email?: string | null;
            /** Phone Number */
            phone_number?: string | null;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Patronymic */
            patronymic?: string | null;
            /** User's password for registration */
            password?: string | null;
            /** User's confirm password for registration */
            confirm_password?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterUserSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSchema_ReadUserSchema_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginUserSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenInfoSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenInfoSchema"];
                };
            };
        };
    };
    check_refresh_token_api_v1_auth_refresh_check_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_authenticated_user_profile_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadUserSchema"];
                };
            };
        };
    };
    update_authenticated_user_profile_api_v1_users_me_update_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateWithPasswordSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSchema_ReadUserSchema_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_messages_list_api_v1_messages__get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSchema_ListPaginatedResponse_ReadMessageSchema__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_message_api_v1_messages__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMessageSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSchema_ReadMessageSchema_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_message_api_v1_messages__message_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSchema_ReadMessageSchema_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_message_api_v1_messages__message_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_categories_list_api_v1_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSchema_list_ReadCategorySchema__"];
                };
            };
        };
    };
    create_category_api_v1_categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategorySchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSchema_ReadCategorySchema_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_categories_list_by_slugs_api_v1_categories_by_slugs_get: {
        parameters: {
            query: {
                slugs: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSchema_list_list_str__str___"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_category_api_v1_categories__category_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_category_api_v1_categories__category_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategorySchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSchema_ReadCategorySchema_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_products_list_api_v1_products_get: {
        parameters: {
            query?: {
                category_slug?: string | null;
                text?: string | null;
                min_price?: number | null;
                max_price?: number | null;
                diameter?: string | null;
                length?: string | null;
                thickness?: string | null;
                angle?: string | null;
                metal_type?: string | null;
                field?: string;
                ordering?: string;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSchema_ListPaginatedResponse_ReadPreviewProductSchema__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_products_by_likes_list_api_v1_products_by_ids_get: {
        parameters: {
            query?: {
                product_ids?: number[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSchema_list_ReadPreviewProductSchema__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_unique_product_list_api_v1_products_unique_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSchema_ListPaginatedResponse_ReadFullUniqueProductSchema__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fetch_filters_api_v1_products_filters_get: {
        parameters: {
            query?: {
                slug?: string | null;
                text?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSchema_ReadFiltersSchema_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_products_recommendations_api_v1_products_popular_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSchema_ListPaginatedResponse_ReadPreviewProductSchema__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fetch_absolute_product_api_v1_products__product_slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSchema_ReadAbsoluteProductSchema_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_product_api_v1_products__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_product_api_v1_products__post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSchema_ReadAbsoluteProductSchema_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_product_api_v1_products__product_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_update_product_api_v1_products__product_id__patch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSchema_ReadAbsoluteProductSchema_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_unique_api_v1_products_unique__unique_product_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                unique_product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cart_api_v1_cart_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSchema_ReadFullCartSchema_"];
                };
            };
        };
    };
    add_to_cart_api_v1_cart_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCartItemWithoutCartIdSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSchema_ReadCartItemSchema_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_cart_item_quantity_api_v1_cart_change_item_quantity__cart_item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cart_item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCartItemQuantity"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSchema_ReadCartItemSchema_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_item_from_cart_api_v1_cart__cart_item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cart_item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_faqs_list_api_v1_faq_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSchema_list_ReadFAQSchema__"];
                };
            };
        };
    };
    create_faq_api_v1_faq_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFAQSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSchema_ReadFAQSchema_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_faq_api_v1_faq__faq_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                faq_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSchema_ReadFAQSchema_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_faq_api_v1_faq__faq_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                faq_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_faq_api_v1_faq__faq_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                faq_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdadeFAQSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSchema_ReadFAQSchema_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_likes_list_api_v1_like_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSchema_list_int__"];
                };
            };
        };
    };
    create_like_api_v1_like_post: {
        parameters: {
            query: {
                product_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSchema_ReadLikeSchema_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_like_api_v1_like__product_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_orders_list_api_v1_orders_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSchema_ListPaginatedResponse_ReadExtendedOrderSchema__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_order_api_v1_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSchema_ReadOrderBaseSchema_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_orders_history_api_v1_orders_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSchema_list_ReadExtendedOrderSchema__"];
                };
            };
        };
    };
    get_active_orders_api_v1_orders_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSchema_list_ReadExtendedOrderSchema__"];
                };
            };
        };
    };
    update_order_info_api_v1_orders__order_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrderSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSchema_ReadOrderBaseSchema_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ping_api_ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PingResponseSchema"];
                };
            };
        };
    };
}
