import { Header } from "@/components/Header/Header";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import './globals.css';
import Footer from "@/components/Footer/Footer";
import { Bounce, ToastContainer } from "react-toastify";
import { CartProvider } from "@/contexts/CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <CartProvider>
          <Header />
          <main className="max-w-screen-2xl mt-20 lg:mt-32 mx-auto px-3">
            {children}
          </main>
          <Footer />
          <ToastContainer
            position="bottom-right"
            theme="light"
            autoClose={3000}
            hideProgressBar={false}
            newestOnTop={false}
            rtl={false}
            transition={Bounce}
            closeOnClick
            pauseOnFocusLoss
            draggable
            pauseOnHover
          />
        </CartProvider>
      </body>
    </html>
  );
}
